"""added faq and image.

Revision ID: 702599f58728
Revises: ec1ef50c4d45
Create Date: 2023-06-10 13:34:19.048471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '702599f58728'
down_revision = 'ec1ef50c4d45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lecturer', schema=None) as batch_op:
        batch_op.drop_column('image')

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.VARCHAR(length=255), nullable=True))

    with op.batch_alter_table('lecturer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
