"""added faq and image.

Revision ID: b8d735afba82
Revises: 702599f58728
Create Date: 2023-06-10 13:38:00.178936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8d735afba82'
down_revision = '702599f58728'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.alter_column('level',
               existing_type=sa.VARCHAR(length=4),
               type_=sa.String(length=6),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.alter_column('level',
               existing_type=sa.String(length=6),
               type_=sa.VARCHAR(length=4),
               existing_nullable=False)

    # ### end Alembic commands ###
