"""deleteted conversation and messages and added chat.

Revision ID: e5f0f47f5c7e
Revises: 18380cd6013f
Create Date: 2023-06-05 11:58:03.362417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5f0f47f5c7e'
down_revision = '18380cd6013f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender', sa.String(length=100), nullable=False),
    sa.Column('receiver', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('message')
    op.drop_table('course')
    op.drop_table('conversation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('student_id', sa.INTEGER(), nullable=False),
    sa.Column('lecturer_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['lecturer_id'], ['lecturer.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('course_name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('course_code', sa.VARCHAR(length=10), nullable=False),
    sa.Column('level', sa.VARCHAR(length=10), nullable=False),
    sa.Column('student_matric_no', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['student_matric_no'], ['student.matric_no'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('conversation_id', sa.INTEGER(), nullable=False),
    sa.Column('sender_id', sa.INTEGER(), nullable=False),
    sa.Column('message', sa.TEXT(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('chat')
    # ### end Alembic commands ###
